version: "3"
services:
  mysql:
    image: mysql:5
    hostname: mysql
    domainname: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db
    tmpfs:
      - /var/lib/mysql:rw